[package]
name = "syn-flood-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "3.1.18",features = ["derive"]}
pnet = "0.31.0"
pnet_transport = "0.31.0"
rand = "0.8.5"
